### ISSUE TITLE
Error en creacion de tabla trabajo

### ISSUE THREAD

**Issue by RComonfort** [JesusLibrado/SIMAC-DB#1]
En  SIMAC-DB/simac.sql , la tabla trabajo marca error de sintaxis en sql, posiblemente relacionado con el tipo enum

![image](https://cloud.githubusercontent.com/assets/18506243/25024622/3e39927e-2064-11e7-8030-f8f301829e61.png)

![image](https://cloud.githubusercontent.com/assets/18506243/25024607/2df1ce86-2064-11e7-8e7d-a4e4e8c512da.png)

**Comment by JesusLibrado** [comment]
Faltaba coma antes de valor 'Suministro'
